### ISSUE TITLE
Error while using agent->update function

### ISSUE THREAD

**Issue by mlisondra** [livechat/api-client-php#10]
Hi, 
I am receiving this error when using the agent update function.

Invalid data input for postBody. Array expected
Here is my call:
$agent_specific = $LiveChatAPI->agents->update(array("name"=>"John Doe"));

I also tried this:
$agent_specific = $LiveChatAPI->agents->update("johndoe@domain.com",array("name"=>"John Doe"));

Thank you for your time.

**Comment by morus12** [comment]
Hi, thank you for finding a bug in our library. 

In previous API versions the agent's id was an integer, now it's agent's email. There was obvious bug - we didn't remove agent's id conversion to integer after switching to agent's email.

Please update your library - your second example should be working fine now.
