### ISSUE TITLE
Fatal error during agents get call

### ISSUE THREAD

**Issue by mlisondra** [livechat/api-client-php#12]
I just updated the library to your most recent version 1.0
However, I get the following when I try to invoke a simple agents get.

Fatal error: Uncaught exception 'Exception' with message 'No such model: agents' in C:\xampp\livechat\src\LiveChat\Api\Client.php:52 Stack trace: #0 C:\xampp\livechat\index.php(9): LiveChat\Api\Client->__get('agents') #1 {main} thrown in C:\xampp\livechat\src\LiveChat\Api\Client.php on line 52

**Comment by HaGii** [comment]
@mlisondra Thanks for the feedback.

Are you sure that autoloader is loaded? Please notice first code line in example:
```php
require_once __DIR__ . '/vendor/autoload.php';
```

**Comment by mlisondra** [comment]
@HaGii  I don't see a file named "autoload.php". 
I'm familiar with the autoload function that's native to PHP 5, though I don't think you are referring to that.
Thank you for the support.

**Comment by HaGii** [comment]
So I suppose that you didn't used [composer](https://getcomposer.org/download/). Am I right?
It's highly recommended to install our client via composer:
````
composer require live chat/api-client-php "@dev"
```
That command creates `vendor/`directory with 3rd part packages and `vendor/autoload.php` file. It also generates composer files (`composer.json` and `composer.lock`).

Hope this helps.

**Comment by mlisondra** [comment]
Andrzej,

You are right, I didn't install using Composer. I must have missed that information.
Let me do that and give it another try.


Thnaks. You guys have great feedback support.



-----Original Message-----

**Comment by mlisondra** [comment]
Andrzej,

You are right, I didn't install using Composer. I must have missed that information.
Let me do that and give it another try.

Thanks. You guys have great feedback support.

**Comment by HaGii** [comment]
Thanks for using LiveChat.
