### ISSUE TITLE
unable to update agent

### ISSUE THREAD

**Issue by mlisondra** [livechat/api-client-php#14]
I have the following code.
Everything works well except when using the update method.
I am passing in the login and an array of parameters as outlined in the github documentation.
However, I don't get a response from the API.
Thanks.

```php
require_once __DIR__ . '/vendor/autoload.php';

use LiveChat\Api\Client as LiveChat;

$LiveChatAPI = new LiveChat('email@domain.com', 'xyz123');
$agents = $LiveChatAPI->agents->get();

foreach($agents as $agent){
	if($agent->login == "myemail@domain.com"){
		print '<pre>';
		print_r($agent);
		print '</pre>';			
	}

}

$LiveChatAPI = new LiveChat('email@domain.com', 'xyz123');
$user_login = "myemail@domain.com";
$user_updates = array("name"=>"Milder Lisondra");
$LiveChatAPI->agents->update($user_login, $user_updates)
```

**Comment by mlisondra** [comment]
Updated the code. But still no change when I go to check the actual user I am trying to update.
Other "get" methods seem to work fine.

require_once __DIR__ . '/vendor/autoload.php';

use LiveChat\Api\Client as LiveChat;

$LiveChatAPI = new LiveChat('email@domain.com', 'xyz123');
$user_login = "milder.lisondra@jewsforjesus.org";
$user_updates = array("login_status"=>"accepting chats");
$result = $LiveChatAPI->agents->update($user_login, array $user_updates);

**Comment by HaGii** [comment]
Hi @mlisondra,

I found your requests for updating agent in our log system. It's looks like requests were succeeded (updated `name` and `login_status`).

Please notice, that API client should returns json or thrown an exception.
Moreover if you want to update an agent, you should use **admin** (or **owner**) e-mail and api key pair. Additionally I noticed typo in your code: 
`$result = $LiveChatAPI->agents->update($user_login, array $user_updates);`, should be:
`$result = $LiveChatAPI->agents->update($user_login, $user_updates);`.

I also improved exception error message. So, please update your vendor and let me know how it works.

**Comment by mlisondra** [comment]
Thank you @HaGii. I noticed my error, too. That was likely the issue but I can't remember if that was the only issue.
