### ISSUE TITLE
Adding annotations

### ISSUE THREAD

**Issue by piotrooo** [livechat/api-client-php#16]
I suggest to add an annotation to the `Client` class, because now PhpStorm highlights that calls:

```php
$this->liveChatApi->chats->get(['visitor_id' => $identifier])
```

This should look like:

```php
/**
 * LiveChat Api Client class.
 * @property \LiveChat\Api\Model\Chats chats
 * @property \LiveChat\Api\Model\Goals goals
 * @property \LiveChat\Api\Model\Agents agents
 * and so on
 */
class Client
{
...
```

Additionally in the model classes there is unused import: `use LiveChat\Api\Model\BaseModel;`.

**Comment by HaGii** [comment]
Cześć Piotrek, dzięki za code review! Usunąłem (https://github.com/livechat/api-client-php/commit/018e1e8dbbb5aff6818c3fc42d43aa27bf2e6f6f) nadmiarowy import z plików modeli. 
Jeśli chodzi o annotacje dedykowane dla IDE, to nie powinny znajdować się one w repozytorium.
