### ISSUE TITLE
Suggestion: add Last Seen attribute in agent information

### ISSUE THREAD

**Issue by mlisondra** [livechat/api-client-php#17]
It would be helpful to include the "last seen" attribute for agent information. This information is displayed when browsing through agents within the normal UI.
Thanks.

**Comment by HaGii** [comment]
Hi @mlisondra, actually there is `last_logout`parameter returned by `$LiveChatAPI->agents->get('agentLogin')`. Example:

```php
$agent = $LiveChatAPI->agents->get('agentLogin');
$lastSeen = $agent->last_logout;
```
