### ISSUE TITLE
ensureInteger() being called on $chatId argument that is of aplha numeric type.

### ISSUE THREAD

**Issue by bbrink68** [livechat/api-client-php#21]
CHAT_ID is a combination of both integers and strings, this effectively doesn't allow me to call, for instance `getSingleChat('FG45GKJ65')` without an exception being thrown.  Removing the call for `ensureInteger()` in each method that accepts a CHAT_ID resolves the issue.

Is there any reason why this is in place when ID's aren't integers?

**Comment by bolchowka** [comment]
@bbrink68 out fault, we'll fix that soon and let you know. ID is not an integer so the validator is incorrect.

**Comment by bbrink68** [comment]
@bolchowka No problem.  If you're strapped for time, I'd be happy to submit a PR.

**Comment by HaGii** [comment]
@bbrink68, thanks for reporting the issue. I removed integer validation. Please see new `v1.1` version.

**Comment by bbrink68** [comment]
Awesome, thanks for the quick turn around on this!
