### ISSUE TITLE
Update Tags Not Working

### ISSUE THREAD

**Issue by cyberian04** [livechat/api-client-php#24]
I am trying to update tags for a chat. Relevant code is
```

$tags=array();
$tags[]="sale";
$LiveChatAPI->chats->updateTags($chat_id,$tags);
```

The request is successful, returns chat data as response but tags are never updated. Tags remain empty.

If I assign tag from admin panel and then update the tags for same chat via API, even those tags are removed.

Looks like some parameters' format issue. Kindly guide ?

**Comment by lukiq** [comment]
Hi cyberian04,

Just change this line:
`$tags[] = "sale";`
to:
`$tags[] = array("tag" => array('sales')).`

Make sure you have tag: `sales` and it should work just fine.

Best Regards,
Luke Powązka
Developer / LiveChat
