### ISSUE TITLE
Live chat fetal error 

### ISSUE THREAD

**Issue by akashkipl** [livechat/api-client-php#27]
With same composer i have tried on other server and its working fine even on localhost its working fine except my server ... , can you please provide me exact php requirement to run this composer so that i will do changes in my server 

When i am trying with the given composer on my server it giving me following error :-1: 

Fatal error: Uncaught exception 'Exception' with message '. ' in /home/chatagents/public_html/lc_api/vendor_new/livechat/api-client-php/src/LiveChat/Api/Rest/RestRequest.php:186 Stack trace: #0 /home/chatagents/public_html/lc_api/vendor_new/livechat/api-client-php/src/LiveChat/Api/Rest/RestRequest.php(157): LiveChat\Api\Rest\RestRequest->throwException(0) #1 /home/chatagents/public_html/lc_api/vendor_new/livechat/api-client-php/src/LiveChat/Api/Model/BaseModel.php(133): LiveChat\Api\Rest\RestRequest->getResponse() #2 /home/chatagents/public_html/lc_api/vendor_new/livechat/api-client-php/src/LiveChat/Api/Model/BaseModel.php(42): LiveChat\Api\Model\BaseModel->executeRequest('GET', 'chats?date_to=2...') #3 /home/chatagents/public_html/lc_api/vendor_new/livechat/api-client-php/src/LiveChat/Api/Model/Chats.php(20): LiveChat\Api\Model\BaseModel->executeGet('chats?date_to=2...') #4 /home/chatagents/public_html/lc_api/akash_api.php(23): LiveChat\Api\Model\Chats->get(Array) #5 {main} thrown in /home/chatagents/public_html/lc_api/vendor_new/livechat/api-client-php/src/LiveChat/Api/Rest/RestRequest.php on line 186

**Comment by lukiq** [comment]
Duplicated issue: https://github.com/livechat/api-client-php/issues/26

**Comment by florenceuguba** [comment]
move_uploaded_file(../uploads/1618318024.jpg): failed to open stream: Permission denied in C:\xampp\htdocs\www\www.premierphysior.com\FINISHED DESIGN\admin\app\gallery.php on line 41

Warning: move_uploaded_file(): Unable to move 'C:\xampp\tmp\phpABE7.tmp' to '../uploads/1618318024.jpg' in C:\xampp\htdocs\www\www.premierphysior.com\FINISHED DESIGN\admin\app\gallery.php on line 41
