### ISSUE TITLE
Webhooks

### ISSUE THREAD

**Issue by michalper** [livechat/api-client-php#31]
Hi,
do You plan to extend API library to webhooks methods?

https://docs.livechatinc.com/rest-api/#webhooks

I really need them to integrate our system with LiveChat and I don't want to create my own lib just for 3 methods.

Plz help :)

**Comment by lukiq** [comment]
Hi @michalper,

we've extended API library to webhooks method.

You can checkout it out in the default branch: https://github.com/livechat/api-client-php/tree/1.1.

Here are sample requests:

- `$LiveChatAPI->webhooks->get()`

- `$LiveChatAPI->webhooks->add(array(
    "event_type" => "chat_started",
    "data_types" => array(
        "chat", "visitor"
    ),
    "url" => "http://www.shoeshop.com/webhook",
))`

- `$LiveChatAPI->webhooks->delete('622d3950eecea8bb5f8c26f20c76ee2e')`

**Comment by michalper** [comment]
Thanks a lot!
